drop table clientes if exists;

create table clientes (
    id bigint generated by default as identity,
    nome varchar(255) not null,
    cep varchar(9) not null,
    logradouro varchar(40) not null,
    complemento varchar(40) not null,
    bairro varchar(40) not null,
    localidade varchar(40) not null,
    uf char(2) not null,
    ativo boolean not null,
    primary key (id)
);
